---

version: '3'

services:

    db:
        image: postgres:14.4-bullseye
        environment:
            POSTGRES_PASSWORD: lvl3
            POSTGRES_USER: project
            POSTGRES_DB: projectlvl3
        volumes:
            - db-data:/var/lib/postgresql
        ports:
            - "127.0.0.1:5123:5432"
        networks:
            - backend

    web:
        restart: always
        build:
            context: .
        command: make start
        ports:
            - "8000:8000"
            - "5137:5137"
        env_file: '.env.example'
        volumes:
            # - "web_static:/web/priv/static"
            - ".:/app"
            # - "~/.bash_history:/root/.bash_history:cached"
            # - ".bashrc:/root/.bashrc:cached"
            - "/tmp:/tmp"
        depends_on:
            - db
        networks:
            - backend

volumes:
    db-data:
    # web_node_modules:
    # web_static:
    # app_build:
    # app_deps:
networks:
    backend:
