name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0.21']

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "copy('.env.testing', '.env');"

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.1

      - name: Setup project
        run: make setup

      - name: Check lint
        run: make lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: build/logs/clover.xml
          fail_ci_if_error: true

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
  deploy:
      needs: build
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' }}
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: php-project-lvl-3 #Must be unique in Heroku
            heroku_email: autlevaslan@yandex.ru
